[tox]
envlist = ruff,pytest
isolated_build = True

[testenv:ruff]
deps =
    ruff>=0.15.0,<0.16.0
skip_install = true
commands =
    ruff check .

[testenv:pytest]
deps =
    pytest>=7.0
commands =
    pytest target_qbwc/tests
