[tox]
envlist = ruff,pytest
isolated_build = True

[testenv:ruff]
deps =
    ruff>=0.15.0,<0.16.0
changedir = {toxinidir}
commands =
    ruff check .

[testenv:pytest]
deps =
    pytest>=7.0
    {[testenv]deps}
commands =
    pytest target_qbwc/tests

[testenv]
deps =
    -e .
